// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeGroup: typeof import('./components/CodeGroup.vue')['default']
    CodeGroupItem: typeof import('./components/CodeGroupItem.vue')['default']
    copy: typeof import('../public/VitesstQB copy.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    ListProjects: typeof import('./components/ListProjects.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PostPager: typeof import('./components/PostPager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepFlow: typeof import('./components/StepFlow.vue')['default']
    StepFlowItem: typeof import('./components/StepFlowItem.vue')['default']
    VitesstQB: typeof import('./components/icons/VitesstQB.vue')['default']
  }
}
